export const SET_TOOLTIPS = 'SET_TOOLTIPS'
export const SAVE_TOOLTIP = 'SAVE_TOOLTIP'

export const DESTROY_TOOLTIP = 'DESTROY_TOOLTIP'

export const TOGGLE_REPLACEMENT = 'TOGGLE_REPLACEMENT'
export const TOGGLE_GLOSSARY    = 'TOGGLE_GLOSSARY'
export const TOGGLE_EDITOR      = 'TOGGLE_EDITOR'
